import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../bloc/purchase_order_bloc.dart';
import '../bloc/purchase_order_event.dart';
import '../data/purchase_order_model.dart';
import 'package:firebase_auth/firebase_auth.dart';

class CreatePurchaseOrderScreen extends StatefulWidget {
  const CreatePurchaseOrderScreen({Key? key}) : super(key: key);

  @override
  _CreatePurchaseOrderScreenState createState() => _CreatePurchaseOrderScreenState();
}

class _CreatePurchaseOrderScreenState extends State<CreatePurchaseOrderScreen> {
  final _formKey = GlobalKey<FormState>();

  final _poNumberCtrl = TextEditingController();
  final _vendorNameCtrl = TextEditingController();
  final _vendorAddressCtrl = TextEditingController();
  final _attentionNameCtrl = TextEditingController();
  final _contactNumberCtrl = TextEditingController();
  final _paymentTermsCtrl = TextEditingController(text: '(Payment terms- Prep)');

  @override
  void initState() {
    super.initState();
    // Auto-generate PO Number: PO-YYMMDD-HHMM
    final now = DateTime.now();
    final year = now.year.toString().substring(2);
    final month = now.month.toString().padLeft(2, '0');
    final day = now.day.toString().padLeft(2, '0');
    final hour = now.hour.toString().padLeft(2, '0');
    final minute = now.minute.toString().padLeft(2, '0');
    _poNumberCtrl.text = 'PO-$year$month$day-$hour$minute';
  }

  List<PurchaseOrderItemModel> _items = [];

  void _addItem() {
    showDialog(
      context: context,
      builder: (ctx) {
        final partCtrl = TextEditingController();
        final descCtrl = TextEditingController();
        final uomCtrl = TextEditingController();
        final priceCtrl = TextEditingController();
        final qtyCtrl = TextEditingController();
        final hsnCtrl = TextEditingController();
        final igstCtrl = TextEditingController(text: '18.0');

        return AlertDialog(
          title: const Text('Add Item'),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(controller: partCtrl, decoration: const InputDecoration(labelText: 'Part Number')),
                TextField(controller: descCtrl, decoration: const InputDecoration(labelText: 'Description')),
                TextField(controller: uomCtrl, decoration: const InputDecoration(labelText: 'UOM (e.g. EA)')),
                TextField(controller: priceCtrl, decoration: const InputDecoration(labelText: 'Special Price'), keyboardType: TextInputType.number),
                TextField(controller: qtyCtrl, decoration: const InputDecoration(labelText: 'Quantity'), keyboardType: TextInputType.number),
                TextField(controller: hsnCtrl, decoration: const InputDecoration(labelText: 'HSN/SAC Code')),
                TextField(controller: igstCtrl, decoration: const InputDecoration(labelText: 'IGST Rate (%)'), keyboardType: TextInputType.number),
              ],
            ),
          ),
          actions: [
            TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
            ElevatedButton(
              onPressed: () {
                setState(() {
                  _items.add(PurchaseOrderItemModel(
                    partNumber: partCtrl.text,
                    description: descCtrl.text,
                    uom: uomCtrl.text,
                    specialPrice: double.tryParse(priceCtrl.text) ?? 0.0,
                    quantity: double.tryParse(qtyCtrl.text) ?? 0.0,
                    hsnCode: hsnCtrl.text,
                    igstRate: double.tryParse(igstCtrl.text) ?? 0.0,
                  ));
                });
                Navigator.pop(ctx);
              },
              child: const Text('Add'),
            ),
          ],
        );
      },
    );
  }

  void _savePO() {
    if (_formKey.currentState!.validate() && _items.isNotEmpty) {
      final po = PurchaseOrderModel(
        id: '', // Generated by bloc
        createdAt: DateTime.now(),
        poNumber: _poNumberCtrl.text,
        vendorName: _vendorNameCtrl.text,
        vendorAddress: _vendorAddressCtrl.text,
        attentionName: _attentionNameCtrl.text,
        contactNumber: _contactNumberCtrl.text,
        items: _items,
        paymentTerms: _paymentTermsCtrl.text,
        createdBy: FirebaseAuth.instance.currentUser?.uid ?? 'unknown',
      );

      context.read<PurchaseOrderBloc>().add(CreatePurchaseOrder(po));
      Navigator.pop(context);
    } else if (_items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please add at least one item')));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create Purchase Order')),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            TextFormField(controller: _poNumberCtrl, decoration: const InputDecoration(labelText: 'PO Number'), validator: (v) => v!.isEmpty ? 'Required' : null),
            TextFormField(controller: _vendorNameCtrl, decoration: const InputDecoration(labelText: 'Vendor Name'), validator: (v) => v!.isEmpty ? 'Required' : null),
            TextFormField(controller: _vendorAddressCtrl, decoration: const InputDecoration(labelText: 'Vendor Address'), maxLines: 3, validator: (v) => v!.isEmpty ? 'Required' : null),
            TextFormField(controller: _attentionNameCtrl, decoration: const InputDecoration(labelText: 'Attention Name')),
            TextFormField(controller: _contactNumberCtrl, decoration: const InputDecoration(labelText: 'Contact Number')),
            TextFormField(controller: _paymentTermsCtrl, decoration: const InputDecoration(labelText: 'Payment Terms')),
            
            const SizedBox(height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('Items', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                ElevatedButton.icon(onPressed: _addItem, icon: const Icon(Icons.add), label: const Text('Add Item')),
              ],
            ),
            const SizedBox(height: 10),
            ..._items.map((item) => Card(
              child: ListTile(
                title: Text('${item.partNumber} - ${item.description}'),
                subtitle: Text('Qty: ${item.quantity} | Price: ₹${item.specialPrice} | IGST: ${item.igstRate}%'),
                trailing: IconButton(
                  icon: const Icon(Icons.delete, color: Colors.red),
                  onPressed: () => setState(() => _items.remove(item)),
                ),
              ),
            )),
            
            const SizedBox(height: 30),
            ElevatedButton(
              style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
              onPressed: _savePO,
              child: const Text('SAVE PURCHASE ORDER', style: TextStyle(fontSize: 16)),
            ),
          ],
        ),
      ),
    );
  }
}
