// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wo1JwkJ4dc3LNJRjQTecVtNIL2WTrIQ',
    appId: '1:593842231374:web:9fbdca735b3ed5c52a8b1f',
    messagingSenderId: '593842231374',
    projectId: 'truptapp',
    authDomain: 'truptapp.firebaseapp.com',
    storageBucket: 'truptapp.firebasestorage.app',
    measurementId: 'G-32TZ5CPLSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzchfmc4woXd2khmvY7_SmnlQ5z-T2wI',
    appId: '1:593842231374:android:f1a799a30c7660e02a8b1f',
    messagingSenderId: '593842231374',
    projectId: 'truptapp',
    storageBucket: 'truptapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWwMEw8kWTEj72KKxPTadBz2Iq__sBd8',
    appId: '1:593842231374:ios:c5a9753e990b18152a8b1f',
    messagingSenderId: '593842231374',
    projectId: 'truptapp',
    storageBucket: 'truptapp.firebasestorage.app',
    iosBundleId: 'com.truptenterprise.truptEnterprise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcWwMEw8kWTEj72KKxPTadBz2Iq__sBd8',
    appId: '1:593842231374:ios:c5a9753e990b18152a8b1f',
    messagingSenderId: '593842231374',
    projectId: 'truptapp',
    storageBucket: 'truptapp.firebasestorage.app',
    iosBundleId: 'com.truptenterprise.truptEnterprise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1wo1JwkJ4dc3LNJRjQTecVtNIL2WTrIQ',
    appId: '1:593842231374:web:d3e33340a27709d02a8b1f',
    messagingSenderId: '593842231374',
    projectId: 'truptapp',
    authDomain: 'truptapp.firebaseapp.com',
    storageBucket: 'truptapp.firebasestorage.app',
    measurementId: 'G-B1KQMHBG4H',
  );
}
